spring.application.name=appointment
server.servlet.context-path=/appointment/api
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

app.url.frontend=https://app-web-appointment.onrender.com
app.mail.from=Acme <onboarding@resend.dev>
app.mail.resend.api-key=re_SwTnVGtE_Pzcvuvkfieapmt7VKSvPybxU
app.files.shift-assigned.path=opt/tmp/appointment/shift-assigned
app.files.shift-assigned.allowed-extensions=pdf
app.files.shift-assigned.max-size-bytes=3145728

spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
