-- schema.sql CORREGIDO
-- Primero eliminar tablas con dependencias
DROP TABLE IF EXISTS day_hour;
DROP TABLE IF EXISTS time_hour;
DROP TABLE IF EXISTS day_week;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS document_type;
DROP TABLE IF EXISTS appointment;


CREATE TABLE document_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    document_type_id BIGINT,
    CONSTRAINT fk_customer_document_type FOREIGN KEY (document_type_id) REFERENCES document_type(id)
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    document_type_id BIGINT,
    CONSTRAINT fk_employee_document_type FOREIGN KEY (document_type_id) REFERENCES document_type(id)
);

CREATE TABLE day_week (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    start_date TIME NOT NULL,
    end_date TIME NOT NULL
);

CREATE TABLE time_hour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL
);


CREATE TABLE day_week_time_hour (
    day_week_id BIGINT NOT NULL,
    time_hour_id BIGINT NOT NULL,
    PRIMARY KEY (day_week_id, time_hour_id),
    CONSTRAINT fk_day_week_time_hour_day FOREIGN KEY (day_week_id) REFERENCES day_week(id) ON DELETE CASCADE,
    CONSTRAINT fk_day_week_time_hour_hour FOREIGN KEY (time_hour_id) REFERENCES time_hour(id) ON DELETE CASCADE
);


CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    date_appointment DATE NOT NULL,
    date_register TIME NOT NULL,
    time_hour_id BIGINT NOT NULL,
    avaible NUMBER,
    CONSTRAINT fk_appointment_time_hour FOREIGN KEY (time_hour_id) REFERENCES time_hour(id)
);

CREATE TABLE shift_assigned (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_register TIME NOT NULL,
    customer_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    appointment_id BIGINT NOT NULL,
    CONSTRAINT fk_shift_assigned_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
    CONSTRAINT fk_shift_assigned_employee FOREIGN KEY (employee_id) REFERENCES employee(id),
    CONSTRAINT fk_shift_assigned_appointment FOREIGN KEY (appointment_id) REFERENCES appointment(id)
);


INSERT INTO document_type (name, description) VALUES
('DNI', 'Documento Nacional de Identidad'),
('PASSPORT', 'Pasaporte');

INSERT INTO employee (name, last_name, dni, email, phone, document_type_id) VALUES
('Juan', 'Perez', '0102030405', 'juan.perez@email.com', '0991234567', 1);

INSERT INTO employee (name, last_name, dni, email, phone, document_type_id) VALUES
('Maria', 'Gomez', '0203040506', 'maria.gomez@email.com', '0987654321', 1);

INSERT INTO employee (name, last_name, dni, email, phone, document_type_id) VALUES
('Carlos', 'Ramirez', '0304050607', 'carlos.ramirez@email.com', '0971122334', 1);


INSERT INTO day_week (name, start_date, end_date) VALUES
('LUNES',     TIME '08:00:00', TIME '17:00:00'),
('MARTES',    TIME '08:00:00', TIME '17:00:00'),
('MIERCOLES', TIME '08:00:00', TIME '17:00:00'),
('JUEVES',    TIME '08:00:00', TIME '17:00:00'),
('VIERNES',   TIME '08:00:00', TIME '17:00:00');


INSERT INTO time_hour (start_time, end_time) VALUES
(TIME '08:00:00', TIME '08:30:00'),
(TIME '08:30:00', TIME '09:00:00'),
(TIME '09:00:00', TIME '09:30:00'),
(TIME '09:30:00', TIME '10:00:00'),
(TIME '10:00:00', TIME '10:30:00'),
(TIME '10:30:00', TIME '11:00:00'),
(TIME '11:00:00', TIME '11:30:00'),
(TIME '11:30:00', TIME '12:00:00'),
(TIME '12:00:00', TIME '12:30:00'),
(TIME '12:30:00', TIME '13:00:00'),
(TIME '13:00:00', TIME '13:30:00'),
(TIME '13:30:00', TIME '14:00:00'),
(TIME '14:00:00', TIME '14:30:00'),
(TIME '14:30:00', TIME '15:00:00'),
(TIME '15:00:00', TIME '15:30:00'),
(TIME '15:30:00', TIME '16:00:00'),
(TIME '16:00:00', TIME '16:30:00'),
(TIME '16:30:00', TIME '17:00:00');

INSERT INTO day_week_time_hour (day_week_id, time_hour_id)
SELECT 1, id FROM time_hour;

INSERT INTO day_week_time_hour (day_week_id, time_hour_id)
SELECT 2, id FROM time_hour;

INSERT INTO day_week_time_hour (day_week_id, time_hour_id)
SELECT 3, id FROM time_hour;

INSERT INTO day_week_time_hour (day_week_id, time_hour_id)
SELECT 4, id FROM time_hour;

INSERT INTO day_week_time_hour (day_week_id, time_hour_id)
SELECT 5, id FROM time_hour;

-- Insert para febrero (días de semana, excluyendo fines de semana)
INSERT INTO appointment (name, date_appointment, date_register, time_hour_id, avaible) VALUES
-- Febrero 2026 - Lunes 2
('Turno 1', '2026-02-02', CURRENT_TIME, 1, 3),
('Turno 2', '2026-02-02', CURRENT_TIME, 2, 3),
('Turno 3', '2026-02-02', CURRENT_TIME, 3, 3),
('Turno 4', '2026-02-02', CURRENT_TIME, 4, 3),
('Turno 5', '2026-02-02', CURRENT_TIME, 5, 3),
('Turno 6', '2026-02-02', CURRENT_TIME, 6, 3),
('Turno 7', '2026-02-02', CURRENT_TIME, 7, 3),
('Turno 8', '2026-02-02', CURRENT_TIME, 8, 3),
('Turno 9', '2026-02-02', CURRENT_TIME, 9, 3),
('Turno 10', '2026-02-02', CURRENT_TIME, 10, 3),
('Turno 11', '2026-02-02', CURRENT_TIME, 11, 3),
('Turno 12', '2026-02-02', CURRENT_TIME, 12, 3),
('Turno 13', '2026-02-02', CURRENT_TIME, 13, 3),
('Turno 14', '2026-02-02', CURRENT_TIME, 14, 3),
('Turno 15', '2026-02-02', CURRENT_TIME, 15, 3),
('Turno 16', '2026-02-02', CURRENT_TIME, 16, 3),
('Turno 17', '2026-02-02', CURRENT_TIME, 17, 3),
('Turno 18', '2026-02-02', CURRENT_TIME, 18, 3),

-- Martes 3
('Turno 19', '2026-02-03', CURRENT_TIME, 1, 3),
('Turno 20', '2026-02-03', CURRENT_TIME, 2, 3),
('Turno 21', '2026-02-03', CURRENT_TIME, 3, 3),
('Turno 22', '2026-02-03', CURRENT_TIME, 4, 3),
('Turno 23', '2026-02-03', CURRENT_TIME, 5, 3),
('Turno 24', '2026-02-03', CURRENT_TIME, 6, 3),
('Turno 25', '2026-02-03', CURRENT_TIME, 7, 3),
('Turno 26', '2026-02-03', CURRENT_TIME, 8, 3),
('Turno 27', '2026-02-03', CURRENT_TIME, 9, 3),
('Turno 28', '2026-02-03', CURRENT_TIME, 10, 3),
('Turno 29', '2026-02-03', CURRENT_TIME, 11, 3),
('Turno 30', '2026-02-03', CURRENT_TIME, 12, 3),
('Turno 31', '2026-02-03', CURRENT_TIME, 13, 3),
('Turno 32', '2026-02-03', CURRENT_TIME, 14, 3),
('Turno 33', '2026-02-03', CURRENT_TIME, 15, 3),
('Turno 34', '2026-02-03', CURRENT_TIME, 16, 3),
('Turno 35', '2026-02-03', CURRENT_TIME, 17, 3),
('Turno 36', '2026-02-03', CURRENT_TIME, 18, 3),

-- Miércoles 4
('Turno 37', '2026-02-04', CURRENT_TIME, 1, 3),
('Turno 38', '2026-02-04', CURRENT_TIME, 2, 3),
('Turno 39', '2026-02-04', CURRENT_TIME, 3, 3),
('Turno 40', '2026-02-04', CURRENT_TIME, 4, 3),
('Turno 41', '2026-02-04', CURRENT_TIME, 5, 3),
('Turno 42', '2026-02-04', CURRENT_TIME, 6, 3),
('Turno 43', '2026-02-04', CURRENT_TIME, 7, 3),
('Turno 44', '2026-02-04', CURRENT_TIME, 8, 3),
('Turno 45', '2026-02-04', CURRENT_TIME, 9, 3),
('Turno 46', '2026-02-04', CURRENT_TIME, 10, 3),
('Turno 47', '2026-02-04', CURRENT_TIME, 11, 3),
('Turno 48', '2026-02-04', CURRENT_TIME, 12, 3),
('Turno 49', '2026-02-04', CURRENT_TIME, 13, 3),
('Turno 50', '2026-02-04', CURRENT_TIME, 14, 3),
('Turno 51', '2026-02-04', CURRENT_TIME, 15, 3),
('Turno 52', '2026-02-04', CURRENT_TIME, 16, 3),
('Turno 53', '2026-02-04', CURRENT_TIME, 17, 3),
('Turno 54', '2026-02-04', CURRENT_TIME, 18, 3),

-- Jueves 5
('Turno 55', '2026-02-05', CURRENT_TIME, 1, 3),
('Turno 56', '2026-02-05', CURRENT_TIME, 2, 3),
('Turno 57', '2026-02-05', CURRENT_TIME, 3, 3),
('Turno 58', '2026-02-05', CURRENT_TIME, 4, 3),
('Turno 59', '2026-02-05', CURRENT_TIME, 5, 3),
('Turno 60', '2026-02-05', CURRENT_TIME, 6, 3),
('Turno 61', '2026-02-05', CURRENT_TIME, 7, 3),
('Turno 62', '2026-02-05', CURRENT_TIME, 8, 3),
('Turno 63', '2026-02-05', CURRENT_TIME, 9, 3),
('Turno 64', '2026-02-05', CURRENT_TIME, 10, 3),
('Turno 65', '2026-02-05', CURRENT_TIME, 11, 3),
('Turno 66', '2026-02-05', CURRENT_TIME, 12, 3),
('Turno 67', '2026-02-05', CURRENT_TIME, 13, 3),
('Turno 68', '2026-02-05', CURRENT_TIME, 14, 3),
('Turno 69', '2026-02-05', CURRENT_TIME, 15, 3),
('Turno 70', '2026-02-05', CURRENT_TIME, 16, 3),
('Turno 71', '2026-02-05', CURRENT_TIME, 17, 3),
('Turno 72', '2026-02-05', CURRENT_TIME, 18, 3),

-- Viernes 6
('Turno 73', '2026-02-06', CURRENT_TIME, 1, 3),
('Turno 74', '2026-02-06', CURRENT_TIME, 2, 3),
('Turno 75', '2026-02-06', CURRENT_TIME, 3, 3),
('Turno 76', '2026-02-06', CURRENT_TIME, 4, 3),
('Turno 77', '2026-02-06', CURRENT_TIME, 5, 3),
('Turno 78', '2026-02-06', CURRENT_TIME, 6, 3),
('Turno 79', '2026-02-06', CURRENT_TIME, 7, 3),
('Turno 80', '2026-02-06', CURRENT_TIME, 8, 3),
('Turno 81', '2026-02-06', CURRENT_TIME, 9, 3),
('Turno 82', '2026-02-06', CURRENT_TIME, 10, 3),
('Turno 83', '2026-02-06', CURRENT_TIME, 11, 3),
('Turno 84', '2026-02-06', CURRENT_TIME, 12, 3),
('Turno 85', '2026-02-06', CURRENT_TIME, 13, 3),
('Turno 86', '2026-02-06', CURRENT_TIME, 14, 3),
('Turno 87', '2026-02-06', CURRENT_TIME, 15, 3),
('Turno 88', '2026-02-06', CURRENT_TIME, 16, 3),
('Turno 89', '2026-02-06', CURRENT_TIME, 17, 3),
('Turno 90', '2026-02-06', CURRENT_TIME, 18, 3);